In [1]:
# import this library in j.notebook
import numpy as np

## Creating an array using numpy

In [2]:
food = np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [3]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(price)

3

In [7]:
len(food)

3

In [8]:
price[2]

5

In [9]:
food[1]

'samosa'

In [10]:
price.mean()

5.0

In [11]:
# zeros method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# specify
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [16]:
# specify interval
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# table of 5
np.arange(0, 50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
# line space
np.linspace(1, 10, num = 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
# specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

## Array function

In [30]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [31]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [32]:
b= np.array([10.2, 3.4, 53.6, 91.6, 45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [33]:
c = np.concatenate((a, b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [34]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

In [35]:
a = np.array([[1,2,3,4,5], [5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [40]:
b = np.array([[6,7,8,9,10], [10,9,8,7,6]])
b

array([[ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [43]:
c = np.concatenate((a,b), axis=0)
c

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [44]:
type(c)

numpy.ndarray

In [45]:
type(b)

numpy.ndarray

In [46]:
c = np.concatenate((a,b), axis=1)
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 5,  4,  3,  2,  1, 10,  9,  8,  7,  6]])

In [56]:
e=np.array([[[0,1,2,3],
           [4,5,6,7]],
           
           [[0,1,2,3],
            [4,5,6,7]],
           
           [[0,1,2,3],
            [4,5,6,7]]])
e

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [57]:
e.ndim

3

In [58]:
e.size

24

In [59]:
e.shape

(3, 2, 4)

In [63]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [68]:
# reshape
b= a.reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [69]:
# convert 1D into 2D
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a.shape

(9,)

In [72]:
# row wise
b= a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [73]:
b.shape

(1, 9)

In [74]:
# column wise
c= a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])